### ISSUE TITLE
Fails to extract

### ISSUE THREAD

**Issue by mrx23dot** [tintinweb/solgrep#1]
Running
`solgrep --find="function.name" test.sol`

on
```
contract ReEntrancyGuard {
    bool internal locked;

    modifier noReentrant() {
        require(!locked, "No re-entrancy");
        locked = true;
        _;
        selfdestruct(343434);
        locked = false;
    }
}

contract ReEntrancyGuard2 {
    bool internal locked;
}

```

gives no results:
```
� SolGrep v0.0.6 ready!

  Enabled Modules:
    ✔️ GenericGrep          _function.name,test.sol

   ────────────────────────────
cheers �
    @tintinweb
    ConsenSys Diligence @ https://consensys.net/diligence/
    https://github.com/tintinweb/solgrep/
```

**Comment by tintinweb** [comment]
Hey @mrx23dot,

`function.name` will currently only work with real functions, not `modifiers`. If there's a use case for you to extract all modifier names we might be able to make that happen in the same fashion. Otherwise there's an example in the Readme that shows how to find specific modifier names 🙌

**Comment by mrx23dot** [comment]
Works great with non-modifiers, thanks!

**Comment by tintinweb** [comment]
the version released today should allow you to extract modifier names too. cheers 🙌

**Comment by mrx23dot** [comment]
Could you also release it on npm then I will give it a go.

Is there an option to dump the AST to file from cli for further processing?
thank you

**Comment by mrx23dot** [comment]
Should  --find="contract.name"  return interface names too?
[02253dfa1f23e72e2e3e1c6b9cd2b8b0a2fc7bc5_SoEToken.txt](https://github.com/tintinweb/solgrep/files/7960531/02253dfa1f23e72e2e3e1c6b9cd2b8b0a2fc7bc5_SoEToken.txt)

**Comment by tintinweb** [comment]
@mrx23dot, yes, it matches interface contracts too. 

<img width="914" alt="image" src="https://user-images.githubusercontent.com/2865694/157009200-5929b737-44c6-48ca-bb63-70bfe5e12364.png">

You can include/exclude interfaces like this:

```
⇒  ./bin/main.js examples/02253dfa1f23e72e2e3e1c6b9cd2b8b0a2fc7bc5_SoEToken.sol --find="contract.name && contract.kind=='interface'" 
```
