### ISSUE TITLE
IsInitializable empty result

### ISSUE THREAD

**Issue by mrx23dot** [tintinweb/solgrep#4]
Hello,

```solgrep 02253dfa1f23e72e2e3e1c6b9cd2b8b0a2fc7bc5_SoEToken.sol --rule=IsInitializable -o out.json```
[02253dfa1f23e72e2e3e1c6b9cd2b8b0a2fc7bc5_SoEToken.txt](https://github.com/tintinweb/solgrep/files/7951567/02253dfa1f23e72e2e3e1c6b9cd2b8b0a2fc7bc5_SoEToken.txt)

gives empty result: {} , I would expect true/false for response.

Could we include IsInitializable into Stats?  It would spare us an extra call.

**Comment by tintinweb** [comment]
Hey @mrx23dot,

I don't have an intention to change this behavior. If the rule does not match it should return an empty object/list which you can easily evaluate to bool if you prefer. I would anyway suggest to use `--output` to dump the full results as json and post-process it 🙌
